### ISSUE TITLE
Linaria loader break webpack "[hash]" for css and js files

### ISSUE THREAD

**Issue by le0pard** [callstack/linaria#512]
## Description

We are using linaria in our project and found, that if our system build assets in different directories, this break webpack `[hash]` for files. 

```js
module.exports = {
  //...
  output: {
    filename: '[name].[hash].bundle.js'
  }
};
```

Why this happend? Linaria using absolute path for build (extracted from ast):

```json
{"ast":null,"code":"import{styled}from'linaria/react';export var FetchErrorMessageBlock=/*#__PURE__*/styled(\"div\")({name:\"FetchErrorMessageBlock\",\"class\":\"f1bh9ktc\"});export var FetchErrorText=/*#__PURE__*/styled(\"div\")({name:\"FetchErrorText\",\"class\":\"feaenko\"});require(\"/var/www/example/releases/20191212093257/tmp/.linaria-cache/app/javascript/src/app/components/fetchErrorMessage/styles.linaria.css\");","map":{"version":3,"sources":["/var/www/example/releases/20191212093257/app/javascript/src/app/components/fetchErrorMessage/styles.js"],"names":["FetchErrorMessageBlock","FetchErrorText"],"mappings":"AAAA,OAAA,MAAA,KAAA,eAAA,CAEA,MAAO,IAAMA,CAAAA,sBAAsB,CAAA,aAAA,MAAA,CAAA,KAAA,CAAA,CAAA,CAAA,IAAA,CAAA,wBAAA,CAAA,QAAA,UAAA,CAAA,CAA5B,CAIP,MAAO,IAAMC,CAAAA,cAAc,CAAA,aAAA,MAAA,CAAA,KAAA,CAAA,CAAA,CAAA,IAAA,CAAA,gBAAA,CAAA,QAAA,SAAA,CAAA,CAApB,C","sourcesContent":["import {styled} from 'linaria/react'\n\nexport const FetchErrorMessageBlock = styled.div`\n  text-align: center;\n`\n\nexport const FetchErrorText = styled.div`\n  margin-bottom: 5px;\n`\n"]},"metadata":{},"sourceType":"module"}
```

As we can see, here two issues, which break source map hash (which influence on files) and js files hash. First part this:

```js
require(\"/var/www/example/releases/20191212093257/tmp/.linaria-cache/app/javascript/src/app/components/fetchErrorMessage/styles.linaria.css\");
```

Webpack loader should not embed absolute paths, because it is break hashes. Here from docs: https://github.com/webpack/docs/wiki/how-to-write-a-loader#should-not-embed-absolute-paths

Next is source map part:

```js
{"version":3,"sources":["/var/www/example/releases/20191212093257/app/javascript/src/app/components/fetchErrorMessage/styles.js"]
```

Issue the same :)

## Reproducible Demo

Make build with linaria. Change dir. Make build again. Hash will be different.

Linaria version: 1.4.0-alpha.1

**Comment by Anber** [comment]
Probably fixed in 1.4.0-beta.1

**Comment by le0pard** [comment]
Thanks for fix @Anber 

Looks like this definitely fix javascript files `[hash]`, but css files still have this issue

![123](https://user-images.githubusercontent.com/98444/72370975-061e3680-370c-11ea-867b-fa546bd45718.png)

If disable css source maps all good:

![234](https://user-images.githubusercontent.com/98444/72371842-d4a66a80-370d-11ea-93b7-85b4f4e47989.png)

Maybe something in css generator depend from path? https://github.com/callstack/linaria/blob/master/src/transform.js

**Comment by Anber** [comment]
@le0pard have you cleaned the linaria cache folder?

**Comment by le0pard** [comment]
@Anber each time it use different folder for linaria cache (like `releases/#{timestamp}/.linaria-cache`)

**Comment by Anber** [comment]
Okay. I've checked it on the default CRA project and everything looked fine. May I ask you to compare css files in your `.linaria-cache`?

**Comment by le0pard** [comment]
Files in `.linaria-cache` had the same content.

Ok, note sure, if css source map difference`[hash]` is linaria fault. It is something wrong together with babel-loader with cache:

https://github.com/rails/webpacker/blob/13756f1ea6b3393117878bb339b9dd507b801eb2/package/rules/babel.js#L15

If you using `cacheDirectory` for babel loader and cleanup this dir each build, it will make hash different. In this dir I found files with such content (looks like AST tree):

```
{"ast":null,"code":"var _createReducer;function _defineProperty(obj,key,value){if(key in obj){Object.defineProperty(obj,key,{value:value,enumerable:true,configurable:true,writable:true});}else{obj[key]=value;}return obj;}import{combineReducers}from'redux';import{createReducer}from'redux-act';import _setWith from'lodash/fp/setWith';import _unset from'lodash/fp/unset';import{corsDomainsCacheKey,sharedInboxesCacheKey,projectCacheKey}from\"../../helpers/httpCache\";import{fetchCorsDomainsSuccess}from\"../../actions/corsDomains\";import{fetchSharedInboxesSuccess}from\"../../actions/sharedInboxes\";import{fetchProjectUsersSuccess}from\"../../actions/projectUsers\";import{fetchProjectInvitesSuccess}from\"../../actions/projectInvites\";import{deleteProjectSuccess,fetchProjectSuccess}from\"../../actions/projects\";var extractHTTPCacheValues=function extractHTTPCacheValues(headers){return{etag:headers['etag'],lastModified:headers['last-modified']};};var setHeadersByCacheKey=function setHeadersByCacheKey(state,cacheKey,headers){return _setWith(Object,cacheKey,extractHTTPCacheValues(headers),state);};var removeHeadersByCacheKey=function removeHeadersByCacheKey(state,cacheKey){return _unset(cacheKey,state);};var cache=createReducer((_createReducer={},_defineProperty(_createReducer,fetchCorsDomainsSuccess,function(state,_ref){var headers=_ref.response.headers;return setHeadersByCacheKey(state,corsDomainsCacheKey(),headers);}),_defineProperty(_createReducer,fetchSharedInboxesSuccess,function(state,_ref2){var headers=_ref2.response.headers;return setHeadersByCacheKey(state,sharedInboxesCacheKey(),headers);}),_defineProperty(_createReducer,fetchProjectSuccess,function(state,_ref3){var id=_ref3.id,headers=_ref3.response.headers;return setHeadersByCacheKey(state,projectCacheKey(id,'project'),headers);}),_defineProperty(_createReducer,deleteProjectSuccess,function(state,_ref4){var id=_ref4.id;return removeHeadersByCacheKey(state,projectCacheKey(id));}),_defineProperty(_createReducer,fetchProjectUsersSuccess,function(state,_ref5){var projectId=_ref5.projectId,headers=_ref5.response.headers;return setHeadersByCacheKey(state,projectCacheKey(projectId,'users'),headers);}),_defineProperty(_createReducer,fetchProjectInvitesSuccess,function(state,_ref6){var projectId=_ref6.projectId,headers=_ref6.response.headers;return setHeadersByCacheKey(state,projectCacheKey(projectId,'invites'),headers);}),_createReducer),{});export var reducer=combineReducers({cache:cache});","map":{"version":3,"sources":["/var/www/falcon-web/releases/20200114185508/app/javascript/src/app/reducers/httpCache/index.js"],"names":["combineReducers","createReducer","_setWith","_unset","corsDomainsCacheKey","sharedInboxesCacheKey","projectCacheKey","fetchCorsDomainsSuccess","fetchSharedInboxesSuccess","fetchProjectUsersSuccess","fetchProjectInvitesSuccess","deleteProjectSuccess","fetchProjectSuccess","extractHTTPCacheValues","headers","etag","lastModified","setHeadersByCacheKey","state","cacheKey","Object","removeHeadersByCacheKey","cache","response","id","projectId","reducer"],"mappings":"yMAAA,OAAQA,eAAR,KAA8B,OAA9B,CACA,OAAQC,aAAR,KAA4B,WAA5B,CACA,MAAOC,CAAAA,QAAP,KAAqB,mBAArB,CACA,MAAOC,CAAAA,MAAP,KAAmB,iBAAnB,CACA,OACEC,mBADF,CAEEC,qBAFF,CAGEC,eAHF,+BAKA,OAAQC,uBAAR,iCACA,OAAQC,yBAAR,mCACA,OAAQC,wBAAR,kCACA,OAAQC,0BAAR,oCACA,OAAQC,oBAAR,CAA8BC,mBAA9B,8BAEA,GAAMC,CAAAA,sBAAsB,CAAG,QAAzBA,CAAAA,sBAAyB,CAACC,OAAD,QAAc,CAC3CC,IAAI,CAAED,OAAO,CAAC,MAAD,CAD8B,CAE3CE,YAAY,CAAEF,OAAO,CAAC,eAAD,CAFsB,CAAd,EAA/B,CAKA,GAAMG,CAAAA,oBAAoB,CAAG,QAAvBA,CAAAA,oBAAuB,CAACC,KAAD,CAAQC,QAAR,CAAkBL,OAAlB,QAC3BZ,CAAAA,QAAQ,CAACkB,MAAD,CAASD,QAAT,CAAmBN,sBAAsB,CAACC,OAAD,CAAzC,CAAoDI,KAApD,CADmB,EAA7B,CAIA,GAAMG,CAAAA,uBAAuB,CAAG,QAA1BA,CAAAA,uBAA0B,CAACH,KAAD,CAAQC,QAAR,QAC9BhB,CAAAA,MAAM,CAACgB,QAAD,CAAWD,KAAX,CADwB,EAAhC,CAIA,GAAMI,CAAAA,KAAK,CAAGrB,aAAa,mDACxBM,uBADwB,CACE,SAACW,KAAD,UAAoBJ,CAAAA,OAApB,MAASS,QAAT,CAAoBT,OAApB,OACzBG,CAAAA,oBAAoB,CAACC,KAAD,CAAQd,mBAAmB,EAA3B,CAA+BU,OAA/B,CADK,EADF,iCAIxBN,yBAJwB,CAII,SAACU,KAAD,WAAoBJ,CAAAA,OAApB,OAASS,QAAT,CAAoBT,OAApB,OAC3BG,CAAAA,oBAAoB,CAACC,KAAD,CAAQb,qBAAqB,EAA7B,CAAiCS,OAAjC,CADO,EAJJ,iCAOxBF,mBAPwB,CAOF,SAACM,KAAD,WAASM,CAAAA,EAAT,OAASA,EAAT,CAAwBV,OAAxB,OAAaS,QAAb,CAAwBT,OAAxB,OACrBG,CAAAA,oBAAoB,CAACC,KAAD,CAAQZ,eAAe,CAACkB,EAAD,CAAK,SAAL,CAAvB,CAAwCV,OAAxC,CADC,EAPE,iCAUxBH,oBAVwB,CAUD,SAACO,KAAD,WAASM,CAAAA,EAAT,OAASA,EAAT,OACtBH,CAAAA,uBAAuB,CAACH,KAAD,CAAQZ,eAAe,CAACkB,EAAD,CAAvB,CADD,EAVC,iCAaxBf,wBAbwB,CAaG,SAACS,KAAD,WAASO,CAAAA,SAAT,OAASA,SAAT,CAA+BX,OAA/B,OAAoBS,QAApB,CAA+BT,OAA/B,OAC1BG,CAAAA,oBAAoB,CAACC,KAAD,CAAQZ,eAAe,CAACmB,SAAD,CAAY,OAAZ,CAAvB,CAA6CX,OAA7C,CADM,EAbH,iCAgBxBJ,0BAhBwB,CAgBK,SAACQ,KAAD,WAASO,CAAAA,SAAT,OAASA,SAAT,CAA+BX,OAA/B,OAAoBS,QAApB,CAA+BT,OAA/B,OAC5BG,CAAAA,oBAAoB,CAACC,KAAD,CAAQZ,eAAe,CAACmB,SAAD,CAAY,SAAZ,CAAvB,CAA+CX,OAA/C,CADQ,EAhBL,kBAmBxB,EAnBwB,CAA3B,CAqBA,MAAO,IAAMY,CAAAA,OAAO,CAAG1B,eAAe,CAAC,CACrCsB,KAAK,CAALA,KADqC,CAAD,CAA/B","sourcesContent":["import {combineReducers} from 'redux'\nimport {createReducer} from 'redux-act'\nimport _setWith from 'lodash/fp/setWith'\nimport _unset from 'lodash/fp/unset'\nimport {\n  corsDomainsCacheKey,\n  sharedInboxesCacheKey,\n  projectCacheKey\n} from 'app/helpers/httpCache'\nimport {fetchCorsDomainsSuccess} from 'app/actions/corsDomains'\nimport {fetchSharedInboxesSuccess} from 'app/actions/sharedInboxes'\nimport {fetchProjectUsersSuccess} from 'app/actions/projectUsers'\nimport {fetchProjectInvitesSuccess} from 'app/actions/projectInvites'\nimport {deleteProjectSuccess, fetchProjectSuccess} from 'app/actions/projects'\n\nconst extractHTTPCacheValues = (headers) => ({\n  etag: headers['etag'],\n  lastModified: headers['last-modified']\n})\n\nconst setHeadersByCacheKey = (state, cacheKey, headers) => (\n  _setWith(Object, cacheKey, extractHTTPCacheValues(headers), state)\n)\n\nconst removeHeadersByCacheKey = (state, cacheKey) => (\n  _unset(cacheKey, state)\n)\n\nconst cache = createReducer({\n  [fetchCorsDomainsSuccess]: (state, {response: {headers}}) => (\n    setHeadersByCacheKey(state, corsDomainsCacheKey(), headers)\n  ),\n  [fetchSharedInboxesSuccess]: (state, {response: {headers}}) => (\n    setHeadersByCacheKey(state, sharedInboxesCacheKey(), headers)\n  ),\n  [fetchProjectSuccess]: (state, {id, response: {headers}}) => (\n    setHeadersByCacheKey(state, projectCacheKey(id, 'project'), headers)\n  ),\n  [deleteProjectSuccess]: (state, {id}) => (\n    removeHeadersByCacheKey(state, projectCacheKey(id))\n  ),\n  [fetchProjectUsersSuccess]: (state, {projectId, response: {headers}}) => (\n    setHeadersByCacheKey(state, projectCacheKey(projectId, 'users'), headers)\n  ),\n  [fetchProjectInvitesSuccess]: (state, {projectId, response: {headers}}) => (\n    setHeadersByCacheKey(state, projectCacheKey(projectId, 'invites'), headers)\n  )\n}, {})\n\nexport const reducer = combineReducers({\n  cache\n})\n"]},"metadata":{},"sourceType":"module"}
```

As you can see, it contain in tree absolute path:

```
"sources":["/var/www/examples/releases/20200114185508/app/javascript/src/app/reducers/httpCache/index.js"]
```

So you can close, if this not linaria fault.

**Comment by le0pard** [comment]
I think we can close this for now. I need better check my environment. Thanks for fix for js hashes again @Anber
