### ISSUE TITLE
Linaria v2.0.0-alpha.1 error: "Cannot read property h1 of undefined"

### ISSUE THREAD

**Issue by jarodpeachey** [callstack/linaria#577]
## Environment

- Linaria version: 2.0.0-alpha.1
- Node.js version: 10.15.1
- OS: Windows 10

## Description

I've just installed the latest Linaria version to get the fix for the core-js issues that have been in Linaria. Those errors have gone away, but the code will not compile properly using the same import statements from the previous version of Linaria.

```
import { styled } from 'linaria/react';
```
When using the import like that, the console says `(Emitted value instead of an instance of Error) TypeError: D:\Jarod\Code\Craft2Care\craft2care\src\components\hero.js: require(...) is not a function`.

I've also tried importing it like this: `import { styled } from 'linaria'`, which compiles, but displays the error `Cannot read property h1 of undefined at 'styled.h1'`.

Is there a new way of importing `styled` since the latest Linaria release?

**Comment by jayu** [comment]
Hi @jarodpeachey thanks for the report. Can you provide reproducible demo, preferably as a GitHub repository? I could not reproduce the issue, `2.0.0-alpha.1` works for me, I just updated from `1.4.0-beta.6`

**Comment by jarodpeachey** [comment]
@jayu Sure. Clone https://github.com/jarodpeachey/craft2care and run `npm install` and `npm start`. You should be able to see the errors

**Comment by jayu** [comment]
It says that I need netlify token. How I can workaround this? 

<img width="648" alt="Screen Shot 2020-04-16 at 17 38 56" src="https://user-images.githubusercontent.com/11561585/79476369-2f02e000-8009-11ea-89e3-bfee8f79bc61.png">

**Comment by jarodpeachey** [comment]
Oh, my bad. I'll push a new commit that you can use that doesn't need the environment variables.

**Comment by jarodpeachey** [comment]
Just pushed, you should be able to get past that error now

**Comment by jayu** [comment]
I have this error now. It seems you did not set up linaria correctly since it is not transpiling your code. 
In `linaria.config.js` some linaria fork `'@brandonkal/linaria/babel'` which seems to be redundant. I'm not sure about your config in general, did you manage to make any previous version of linaria work in your project? 
Please make sure that you setup Linaria correctly and then we can verify if this is a real bug :)

If you are using https://github.com/silvenon/gatsby-plugin-linaria it seems you don't need `linaria.config.js` at all. Maybe try to integrate linaria to fresh gatsby project and try to set up linaria there to avoid any other issues that your current setup may introduce. Then you could compare them and verify why it does not work. I would love to help but cannot repro your issue :(

<img width="1019" alt="Screen Shot 2020-04-16 at 18 04 30" src="https://user-images.githubusercontent.com/11561585/79479278-d3d2ec80-800c-11ea-82a8-7494351831bb.png">

**Comment by jarodpeachey** [comment]
Ok. I've removed that other package, but now it won't compile. It says 
```
(Emitted value instead of an instance of Error) TypeError: D:\Jarod\Code\Craft2Care\craft2care\src\components\hero.js: require(...) is not a function
```

wherever I import { styled } from linaria/react.

**Comment by jayu** [comment]
First of all please add `babel.config.js` file with following content
```
module.exports = {
  presets: [
    'babel-preset-gatsby',
    [
      'linaria/babel',
      {
        evaluate: true,
      }
    ],
  ],
};
```
Otherwise Linaria will not work. In my case I get an error that indicates that Linaria is not configured correctly (missing babel plugin setup). Once I fixed it I get other errors related your codebase.

I'm on Unix system so maybe the environment makes the difference in what is the error message. 

Your repro has too complex config to be sure that it is really an issue with Linaria. Once again, please try to bootstrap a new gatsby project, setup linaria there and port working config to project that you claim to not work with Linaria. Then we can start thinking about what's not working.

**Comment by jayu** [comment]
@jarodpeachey Did you manage to solve the issue?

**Comment by jarodpeachey** [comment]
Hey @jayu sorry for the delay in responding. I've tried getting it to work on a basic gatsby starter and it still won't compile. It says 

```
> 47 | const StyleWrapper = styled.div`
     |                                                  ^   
  48 |   display: flex;
  49 |   flex-direction: column;
  50 |   justify-content: flex-start;


  WebpackError: TypeError: linaria_react__WEBPACK_IMPORTED_MODULE_2___default.a.div is not a function
```
